# Generated by Django 2.1.2 on 2018-12-11 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='member',
            name='image',
        ),
    ]
