# Generated by Django 2.1.2 on 2018-12-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20181208_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='profile',
        ),
        migrations.AlterField(
            model_name='profile',
            name='text',
            field=models.EmailField(max_length=4096),
        ),
    ]
