# Generated by Django 2.1.2 on 2018-12-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_member_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='image',
            field=models.ImageField(default='4.png', upload_to='profile_images'),
            preserve_default=False,
        ),
    ]
