# Generated by Django 2.1.2 on 2018-12-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_member_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='following',
            field=models.ManyToManyField(blank=True, to='mainapp.Member'),
        ),
    ]
