# Generated by Django 2.1.2 on 2018-12-08 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20181208_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='text',
            field=models.CharField(max_length=4096),
        ),
    ]
