# Generated by Django 2.1.2 on 2018-12-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20181208_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='text',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='asd@gmail.com', max_length=4096),
            preserve_default=False,
        ),
    ]
