# Generated by Django 2.1.3 on 2018-12-08 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20181208_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
